### ISSUE TITLE
UDict indices and keys conflict

### ISSUE THREAD

**Issue by moontr3** [honey-team/ufpy#8]
You can get a value from a dict by using `dict[x]` with either index or a key.

```py
dict = UDict(foo=1, bar=2)
dict["foo"] # 1
dict[1] # 1
dict[-1] # 2
```

In inbuilt dicts, you can actually use `int`s as a key:

```py
dict = {1: "foo", 2: "bar"}
dict[1] # foo
dict[2] # bar
```

So, if you do something like this, you will get the value by the key, not index:

```py
dict = UDict({2: "foo", 1: "bar"})
dict[1] # bar
```

But what if you _reeeeally_ want to get a value by an index, not a key? This definitely needs a fix.

I propose the following solution:

```py
dict.get(index=1) # foo
dict.get(key=1) # bar
```

**Comment by moontr3** [comment]
And don't forget about the `default` feature of the inbuilt `dict.get()`

**Comment by bleudev** [comment]
> And don't forget about the `default` feature of the inbuilt `dict.get()`

Thanks for your issue. I'll fix that soon
